modules:
  https:
#    port: 8080
    path: ../lib/libhttps_module.so
    port: 3000
    certificatePath: ../certificate/server.crt
    certificateKey: ../certificate/server.key
    certificateDhFile: ../certificate/dh2048.pem
    certificateKeyPassword: password
#    path: http_module.dll
  staticserve:
    path: static_serve.dll
#    cgiPath: C:\Program Files\Python310\python.exe
#    path: cgi.dll
#    cgiPath: ../../php/php-cgi.exe
    rootDirectory: ../../files
    dirpath: .
