modules:
  https:
    port: 8080
    path: ./../lib/libhttps_module.so
    port: 3000
    certificatePath: ../certificate/server.crt
    certificateKey: ../certificate/server.key
    certificateDhFile: ../certificate/dh2048.pem
    certificateKeyPassword: password
#    path: http_module.dll
#  staticserve:
#    path: ./../lib/libstatic_serve.so
#    dirpath: .
