modules:
    phpCGI:
        foo: bar
        bar: baz
        baz: qux
        qux: quux
        quux: quuz
    networksTLS:
        ip: plouf
        location: /etc/nginx/certs
        id: 1234
        